//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserSettings.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserSettings.Resources.GeneralStrings", typeof(GeneralStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acceleration, m/s^2.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Air.
        /// </summary>
        public static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aluminium.
        /// </summary>
        public static string Aluminium {
            get {
                return ResourceManager.GetString("Aluminium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approach normal.
        /// </summary>
        public static string ApproachNormal {
            get {
                return ResourceManager.GetString("ApproachNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approach precut.
        /// </summary>
        public static string ApproachPrecut {
            get {
                return ResourceManager.GetString("ApproachPrecut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approach red acc.
        /// </summary>
        public static string ApproachRedAcc {
            get {
                return ResourceManager.GetString("ApproachRedAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approach red speed.
        /// </summary>
        public static string ApproachRedSpeed {
            get {
                return ResourceManager.GetString("ApproachRedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approach red speed acc.
        /// </summary>
        public static string ApproachRedSpeedAcc {
            get {
                return ResourceManager.GetString("ApproachRedSpeedAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beam diameter, mm.
        /// </summary>
        public static string BeamDiameter {
            get {
                return ResourceManager.GetString("BeamDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large contour.
        /// </summary>
        public static string BigContour {
            get {
                return ResourceManager.GetString("BigContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brass.
        /// </summary>
        public static string Brass {
            get {
                return ResourceManager.GetString("Brass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Burning time.
        /// </summary>
        public static string BurningTime {
            get {
                return ResourceManager.GetString("BurningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Burning type.
        /// </summary>
        public static string BurningType {
            get {
                return ResourceManager.GetString("BurningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Burn normal.
        /// </summary>
        public static string BurnNormal {
            get {
                return ResourceManager.GetString("BurnNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Burn soft.
        /// </summary>
        public static string BurnSoft {
            get {
                return ResourceManager.GetString("BurnSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coefficient.
        /// </summary>
        public static string Coefficient {
            get {
                return ResourceManager.GetString("Coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Colim lens temperature,, ℃.
        /// </summary>
        public static string ColimLensTemperature {
            get {
                return ResourceManager.GetString("ColimLensTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cooling.
        /// </summary>
        public static string Cooling {
            get {
                return ResourceManager.GetString("Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cooper.
        /// </summary>
        public static string Cooper {
            get {
                return ResourceManager.GetString("Cooper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cutting gas pressure, bar.
        /// </summary>
        public static string CuttingGasPressure {
            get {
                return ResourceManager.GetString("CuttingGasPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Electrical steel.
        /// </summary>
        public static string ElectricalSteel {
            get {
                return ResourceManager.GetString("ElectricalSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Engraving.
        /// </summary>
        public static string Engraving {
            get {
                return ResourceManager.GetString("Engraving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Evaporation.
        /// </summary>
        public static string Evaporation {
            get {
                return ResourceManager.GetString("Evaporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedrate, mm/min.
        /// </summary>
        public static string Feedrate {
            get {
                return ResourceManager.GetString("Feedrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Focal configuration number.
        /// </summary>
        public static string FocalConfigNumber {
            get {
                return ResourceManager.GetString("FocalConfigNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Focal lens temperature, ℃.
        /// </summary>
        public static string FocalLensTemperature {
            get {
                return ResourceManager.GetString("FocalLensTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Following.
        /// </summary>
        public static string FollowingOn {
            get {
                return ResourceManager.GetString("FollowingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gap, mm.
        /// </summary>
        public static string Gap {
            get {
                return ResourceManager.GetString("Gap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gas pressure, bar.
        /// </summary>
        public static string GasPressure {
            get {
                return ResourceManager.GetString("GasPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gas type.
        /// </summary>
        public static string GasType {
            get {
                return ResourceManager.GetString("GasType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ▶.
        /// </summary>
        public static string HtmlEntity {
            get {
                return ResourceManager.GetString("HtmlEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imp duty cycle, %.
        /// </summary>
        public static string ImpDutyCycle {
            get {
                return ResourceManager.GetString("ImpDutyCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imp frequency, Hz.
        /// </summary>
        public static string ImpFrequeency {
            get {
                return ResourceManager.GetString("ImpFrequeency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large contour.
        /// </summary>
        public static string LargeContour {
            get {
                return ResourceManager.GetString("LargeContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Focus, mm.
        /// </summary>
        public static string LaserFocus {
            get {
                return ResourceManager.GetString("LaserFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Laser head control values.
        /// </summary>
        public static string LaserHeadControlValues {
            get {
                return ResourceManager.GetString("LaserHeadControlValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Laser head temperature, ℃.
        /// </summary>
        public static string LaserHeadTemperature {
            get {
                return ResourceManager.GetString("LaserHeadTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Laser power, W.
        /// </summary>
        public static string LaserPower {
            get {
                return ResourceManager.GetString("LaserPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LASER SETTINGS.
        /// </summary>
        public static string LaserSettingsTitle {
            get {
                return ResourceManager.GetString("LaserSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lens current position.
        /// </summary>
        public static string LensCurrentPosition {
            get {
                return ResourceManager.GetString("LensCurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microweld hard.
        /// </summary>
        public static string MicroweldHard {
            get {
                return ResourceManager.GetString("MicroweldHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microweld soft.
        /// </summary>
        public static string MicroweldSoft {
            get {
                return ResourceManager.GetString("MicroweldSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle contour.
        /// </summary>
        public static string MiddleContour {
            get {
                return ResourceManager.GetString("MiddleContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimal power, W.
        /// </summary>
        public static string MinLaserPower {
            get {
                return ResourceManager.GetString("MinLaserPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nitrogen.
        /// </summary>
        public static string Nitrogen {
            get {
                return ResourceManager.GetString("Nitrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nozzle diameter, mm.
        /// </summary>
        public static string NozzleDiameter {
            get {
                return ResourceManager.GetString("NozzleDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error happens during file opening.
        /// </summary>
        public static string OpeningError {
            get {
                return ResourceManager.GetString("OpeningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other parameters.
        /// </summary>
        public static string OtherParameters {
            get {
                return ResourceManager.GetString("OtherParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oxygen.
        /// </summary>
        public static string Oxygen {
            get {
                return ResourceManager.GetString("Oxygen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power of the ray refraction.
        /// </summary>
        public static string PowerOfRefraction {
            get {
                return ResourceManager.GetString("PowerOfRefraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pre burn.
        /// </summary>
        public static string PreBurn {
            get {
                return ResourceManager.GetString("PreBurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressure inside the head, bar.
        /// </summary>
        public static string PressureInsideHead {
            get {
                return ResourceManager.GetString("PressureInsideHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protective window temperature, ℃.
        /// </summary>
        public static string ProtectiveWindowTemp {
            get {
                return ResourceManager.GetString("ProtectiveWindowTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Punching.
        /// </summary>
        public static string Punching {
            get {
                return ResourceManager.GetString("Punching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ramp number.
        /// </summary>
        public static string RampNo {
            get {
                return ResourceManager.GetString("RampNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rounded on.
        /// </summary>
        public static string RoundedOn {
            get {
                return ResourceManager.GetString("RoundedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error happens during file saving.
        /// </summary>
        public static string SavingError {
            get {
                return ResourceManager.GetString("SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sensor sensitivity 1.
        /// </summary>
        public static string SensorSensitivityI1 {
            get {
                return ResourceManager.GetString("SensorSensitivityI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sensor sensitivity 2.
        /// </summary>
        public static string SensorSensitivityI2 {
            get {
                return ResourceManager.GetString("SensorSensitivityI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small contour.
        /// </summary>
        public static string SmallContour {
            get {
                return ResourceManager.GetString("SmallContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stainless steel.
        /// </summary>
        public static string StainlessSteel {
            get {
                return ResourceManager.GetString("StainlessSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Steel.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Titanium.
        /// </summary>
        public static string Titanium {
            get {
                return ResourceManager.GetString("Titanium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Z offset correction.
        /// </summary>
        public static string ZCorrection {
            get {
                return ResourceManager.GetString("ZCorrection", resourceCulture);
            }
        }
    }
}
